"""Collect Wikipedia article text for specific topics; no PDFs or link crawling.

Install: python -m pip install requests beautifulsoup4 pyyaml
Run:     python collect_wiki.py --config day2.yaml
         python collect_wiki.py --config day2.yaml --all-topics --max-pages 0
         python collect_wiki.py --config day2.yaml --topic "Transformer (deep learning)"

Repeat --topic for multiple topics. Otherwise use data.wiki_topics from your
existing YAML, or WIKI_SEEDS below. --all-topics merges all built-in topics with
your YAML topics. --max-pages 0 removes the YAML page cap for this run.
Candidate titles are not a guarantee of distinct articles or a token budget.
Requires your existing dataio.py for config
loading and JSONL writing. No related files are generated by this script.
Output: paths.raw_dir/domain_wikipedia.jsonl (replaced on a successful run).

Run this BEFORE collect.py, then run:  collect.py --config day2.yaml --skip-wiki
(so collect.py leaves this file untouched and adds arXiv + docs + replay).
"""

import argparse
from datetime import datetime, timezone
from pathlib import Path
import re
import time

import requests
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

API_URL = "https://en.wikipedia.org/w/api.php"

# Curated topic list (transformer/LLM-centric + NN foundations). Manage topics
# here or via data.wiki_topics in the YAML. Add more titles for more volume --
# every article is one you chose, which keeps the corpus on-topic.
WIKI_SEEDS = [
    'Transformer (deep learning)',
    'Attention (machine learning)',
    'Attention Is All You Need',
    'Multi-head attention',
    'Self-attention',
    'Positional encoding',
    'Large language model',
    'Language model',
    'Generative pre-trained transformer',
    'GPT-2',
    'GPT-3',
    'GPT-4',
    'BERT (language model)',
    'T5 (language model)',
    'Vision transformer',
    'Masked language model',
    'Autoregressive model',
    'Sequence to sequence',
    'Encoder-decoder',
    'Neural machine translation',
    'Foundation model',
    'Generative artificial intelligence',
    'Text generation',
    'Tokenization (lexical analysis)',
    'Byte pair encoding',
    'Word embedding',
    'Word2vec',
    'Embedding',
    'Beam search',
    'N-gram language model',
    'Fine-tuning (deep learning)',
    'Transfer learning',
    'Pretraining',
    'Self-supervised learning',
    'Reinforcement learning from human feedback',
    'In-context learning (natural language processing)',
    'Prompt engineering',
    'Zero-shot learning',
    'Few-shot learning',
    'Knowledge distillation',
    'Low-rank adaptation',
    'Mixture of experts',
    'Instruction tuning',
    'Artificial neural network',
    'Deep learning',
    'Feedforward neural network',
    'Multilayer perceptron',
    'Recurrent neural network',
    'Long short-term memory',
    'Gated recurrent unit',
    'Backpropagation',
    'Gradient descent',
    'Stochastic gradient descent',
    'Activation function',
    'Softmax function',
    'Rectifier (neural networks)',
    'Layer normalization',
    'Batch normalization',
    'Residual neural network',
    'Dropout (neural networks)',
    'Loss function',
    'Cross entropy',
    'Adam (optimization algorithm)',
    'Learning rate',
    'Vanishing gradient problem',
    'Regularization (mathematics)',
    'Overfitting',
    'Automatic differentiation',
    'Chain rule',
    'Natural language processing',
    'Machine learning',
    'Supervised learning',
    'Neural scaling law',
    'Hallucination (artificial intelligence)',
    'Perplexity',
    'Chatbot',
    'Question answering',
    'GPT-1',
    'GPT-J',
    'GPT-Neo',
    'LLaMA (language model)',
    'PaLM',
    'Gemini (language model)',
    'Claude (language model)',
    'Mistral AI',
    'BLOOM (language model)',
    'OPT (language model)',
    'Chinchilla (language model)',
    'GPT-4o',
    'ChatGPT',
    'RoBERTa',
    'DistilBERT',
    'ALBERT (language model)',
    'ELECTRA (machine learning)',
    'XLNet',
    'ELMo',
    'ULMFiT',
    'Whisper (speech recognition system)',
    'DALL-E',
    'Stable Diffusion',
    'CLIP (machine learning)',
    'Segment Anything Model',
    'Swin Transformer',
    'ConvNeXt',
    'Attention mechanism',
    'Cross-attention',
    'Flash attention',
    'Rotary position embedding',
    'Feedforward network',
    'Convolutional neural network',
    'Deep belief network',
    'Autoencoder',
    'Variational autoencoder',
    'Generative adversarial network',
    'Diffusion model',
    'Graph neural network',
    'Capsule neural network',
    'Highway network',
    'Sequence model',
    'State space model',
    'Mamba (deep learning)',
    'Reinforcement learning',
    'Direct preference optimization',
    'Proximal policy optimization',
    'Policy gradient method',
    'Q-learning',
    'Actor-critic algorithm',
    'Contrastive learning',
    'Curriculum learning',
    'Meta-learning (computer science)',
    'Federated learning',
    'Online machine learning',
    'Active learning (machine learning)',
    'Semi-supervised learning',
    'Unsupervised learning',
    'Multi-task learning',
    'Continual learning',
    'Catastrophic interference',
    'Early stopping',
    'Hyperparameter optimization',
    'Bayesian optimization',
    'Grid search',
    'Momentum (machine learning)',
    'RMSprop',
    'AdaGrad',
    'Weight decay',
    'Gradient clipping',
    'Learning rate schedule',
    'Warmup (machine learning)',
    'Mixed precision',
    'Quantization (machine learning)',
    'Pruning (artificial neural network)',
    'Weight initialization',
    'Xavier initialization',
    'WordPiece',
    'SentencePiece',
    'Subword tokenization',
    'Bag-of-words model',
    'TF-IDF',
    'GloVe (machine learning)',
    'FastText',
    'Contextual word embeddings',
    'Sentence embedding',
    'Named-entity recognition',
    'Part-of-speech tagging',
    'Coreference resolution',
    'Text summarization',
    'Machine translation',
    'Sentiment analysis',
    'Language understanding',
    'Natural language generation',
    'Semantic search',
    'Information retrieval',
    'Retrieval-augmented generation',
    'BLEU',
    'ROUGE (metric)',
    'Word error rate',
    'F-score',
    'Linear algebra',
    'Matrix multiplication',
    'Dot product',
    'Tensor',
    'Vector space',
    'Eigenvalues and eigenvectors',
    'Probability distribution',
    "Bayes' theorem",
    'Maximum likelihood estimation',
    'Kullback–Leibler divergence',
    'Entropy (information theory)',
    'Information theory',
    'Sigmoid function',
    'Hyperbolic tangent',
    'Rectified linear unit',
    'Gaussian function',
    'Normal distribution',
    'Convex optimization',
    'Stochastic process',
    'Markov chain',
    'Hidden Markov model',
    'Dimensionality reduction',
    'Principal component analysis',
    'PyTorch',
    'TensorFlow',
    'JAX (software)',
    'Keras',
    'Hugging Face',
    'CUDA',
    'Graphics processing unit',
    'Tensor Processing Unit',
    'Automatic mixed precision',
    'Distributed computing',
    'Data parallelism',
    'Model parallelism',
    'ONNX',
    'Artificial intelligence',
    'Machine perception',
    'Explainable artificial intelligence',
    'AI alignment',
    'AI safety',
    'Bias–variance tradeoff',
    'Generalization error',
    'Training, validation, and test data sets',
    'Cross-validation (statistics)',
    'Confusion matrix',
    'Precision and recall',
    'Receiver operating characteristic',
    'Emergent abilities of large language models',
    'Scaling laws',
    'Reasoning language model',
    'Chain-of-thought prompting',
    'Multimodal learning',
    'Speech recognition',
    'Optical character recognition',
    'Computer vision',
]

# Additional candidate titles, grouped by subject. Some topics have no
# standalone Wikipedia article; redirects are deduplicated and failures
# are logged. Search-based matches still need relevance review.
EXTRA_WIKI_TOPICS = [
    # Transformer architecture and attention
    'Neural attention',
    'Attention layer',
    'Sparse attention',
    'Linear attention',
    'Grouped-query attention',
    'Multi-query attention',
    'Sliding window attention',
    'Relative positional encoding',
    'ALiBi',
    'Transformer-XL',
    'Longformer',
    'Reformer (model)',
    'Linformer',
    'Performer (machine learning)',
    'BigBird (model)',
    'Universal transformer',
    'Perceiver',
    'Retentive network',
    'RWKV',
    'Neural Turing machine',
    'Differentiable neural computer',
    'Memory network',
    'Neural architecture search',
    'Neural architecture',
    'Skip connection',
    'RMSNorm',
    'Gated linear unit',
    'Gaussian error linear unit',
    'Swish function',
    'SwiGLU',
    # Language model families and research systems
    'GPT (language model)',
    'GPT-NeoX',
    'GPT-4.1',
    'GPT-4.5',
    'GPT-5',
    'OpenAI o1',
    'OpenAI o3',
    'OpenAI o4-mini',
    'Qwen',
    'DeepSeek',
    'DeepSeek-R1',
    'DeepSeek-V3',
    'Gemma (language model)',
    'Phi (language model)',
    'Falcon (language model)',
    'Mixtral',
    'Mistral (language model)',
    'Mistral Large',
    'Llama 2',
    'Llama 3',
    'Code Llama',
    'Code Llama (language model)',
    'Llama 4',
    'OLMo',
    'DBRX',
    'Grok (chatbot)',
    'ERNIE Bot',
    'Command R',
    'Jamba (language model)',
    'Jurassic-1',
    'LaMDA',
    'MT-NLG',
    'Megatron-Turing Natural Language Generation',
    'Megatron-LM',
    'Gopher (language model)',
    'Sparrow (chatbot)',
    'Minerva (language model)',
    'Galactica (language model)',
    'Chameleon (language model)',
    'OpenELM',
    'SmolLM',
    'OpenAI Codex',
    'StarCoder',
    'CodeGen (language model)',
    'CodeT5',
    'CodeBERT',
    'GraphCodeBERT',
    'PLBART',
    'BART (language model)',
    'DeBERTa',
    'CamemBERT',
    'FlauBERT',
    'XLM-RoBERTa',
    'ERNIE (language model)',
    'MPNet',
    'Sentence-BERT',
    'MASS (language model)',
    'UL2',
    'Flan-T5',
    'mT5',
    'ByT5',
    # Pretraining, adaptation, alignment and reasoning
    'Causal language modeling',
    'Denoising autoencoder',
    'Language model pre-training',
    'Domain adaptation',
    'Domain generalization',
    'Parameter-efficient fine-tuning',
    'Adapter (machine learning)',
    'Prompt tuning',
    'Prefix tuning',
    'QLoRA',
    'DoRA (machine learning)',
    'Supervised fine-tuning',
    'Reinforcement learning from AI feedback',
    'Constitutional AI',
    'Preference learning',
    'Reward model',
    'Reward hacking',
    'Inverse reinforcement learning',
    'Offline reinforcement learning',
    'Group relative policy optimization',
    'Trust region policy optimization',
    'REINFORCE algorithm',
    'Advantage actor-critic',
    'Asynchronous advantage actor-critic',
    'Monte Carlo tree search',
    'Tree of thoughts',
    'Chain-of-thought',
    'Test-time compute',
    'Test-time training',
    'Knowledge editing',
    'Model editing',
    'Machine unlearning',
    'Model merging',
    'Multi-agent system',
    'Intelligent agent',
    'Language agent',
    'Toolformer',
    'ReAct (prompting)',
    'Program synthesis',
    'Neuro-symbolic AI',
    'Automated reasoning',
    'Mathematical reasoning',
    # Tokenization, decoding, representation and retrieval
    'Statistical language model',
    'Neural language model',
    'Subword',
    'Unigram',
    'Sentence segmentation',
    'Text normalization',
    'Unicode normalization',
    'Byte-level byte pair encoding',
    'Vocabulary (machine learning)',
    'Out-of-vocabulary',
    'Distributional semantics',
    'Vector semantics',
    'Distributed representation',
    'Representation learning',
    'Embedding space',
    'Cosine similarity',
    'Latent semantic analysis',
    'Latent semantic indexing',
    'Non-negative matrix factorization',
    'Doc2vec',
    'Sentence encoder',
    'Vector database',
    'Vector search',
    'Nearest neighbor search',
    'Approximate nearest neighbor search',
    'Hierarchical navigable small world',
    'Product quantization',
    'Maximum inner-product search',
    'Okapi BM25',
    'Learning to rank',
    'Relevance (information retrieval)',
    'Dense passage retrieval',
    'Reciprocal rank fusion',
    'Cross-encoder',
    'Bi-encoder',
    'Context window',
    'Prompt caching',
    'KV cache',
    'Speculative decoding',
    'Nucleus sampling',
    'Top-k sampling',
    'Temperature (machine learning)',
    'Exposure bias',
    'Teacher forcing',
    'Scheduled sampling',
    'Greedy algorithm',
    'Viterbi algorithm',
    # Training efficiency, optimization and numerical foundations
    'Gradient accumulation',
    'Activation checkpointing',
    'Gradient checkpointing',
    'Pipeline parallelism',
    'Tensor parallelism',
    'Sequence parallelism',
    'Fully sharded data parallelism',
    'DeepSpeed',
    'ZeRO (deep learning)',
    'Horovod (software)',
    'Allreduce',
    'Collective operation',
    'NCCL',
    'Bfloat16 floating-point format',
    'Half-precision floating-point format',
    'Floating-point arithmetic',
    'Loss scaling',
    'Arithmetic intensity',
    'Roofline model',
    'Kernel fusion',
    'Triton (programming language)',
    'vLLM',
    'Llama.cpp',
    'GGML',
    'ONNX Runtime',
    'TensorRT',
    'TensorRT-LLM',
    'Model compression',
    'Post-training quantization',
    'Quantization-aware training',
    'GPTQ',
    'AWQ (quantization)',
    'Sparse matrix',
    'Sparsity',
    'Low-rank approximation',
    'Singular value decomposition',
    'Numerical stability',
    'LogSumExp',
    'Jacobian matrix and determinant',
    'Hessian matrix',
    'Matrix calculus',
    'Reverse-mode automatic differentiation',
    'Gradient',
    'Gradient noise scale',
    'Natural gradient',
    'Second-order optimization',
    'L-BFGS',
    'AdamW',
    'Adafactor',
    'Lion (optimizer)',
    'Sharpness-aware minimization',
    'Cosine annealing',
    'Polyak averaging',
    'Stochastic weight averaging',
    'Label smoothing',
    'Elastic weight consolidation',
    'Experience replay',
    # Evaluation, datasets, interpretability and robustness
    'Language model evaluation',
    'MMLU',
    'GLUE benchmark',
    'SuperGLUE',
    'BIG-bench',
    'HELM (benchmark)',
    'HumanEval',
    'MBPP',
    'GSM8K',
    'MATH (dataset)',
    'HellaSwag',
    'Winograd schema challenge',
    'ARC (AI benchmark)',
    'AI2 Reasoning Challenge',
    'SQuAD',
    'Natural Questions',
    'TriviaQA',
    'TruthfulQA',
    'WinoGrande',
    'LAMBADA',
    'WikiText',
    'Penn Treebank',
    'The Pile (dataset)',
    'Common Crawl',
    'C4 (dataset)',
    'RedPajama',
    'FineWeb',
    'Dolma (dataset)',
    'ROOTS (dataset)',
    'RefinedWeb',
    'BookCorpus',
    'LAION',
    'Data augmentation',
    'Synthetic data',
    'Data quality',
    'Data cleaning',
    'Data deduplication',
    'Data curation',
    'Data leakage',
    'Benchmark (computing)',
    'Calibration (statistics)',
    'Brier score',
    'Expected calibration error',
    'Distribution shift',
    'Out-of-distribution detection',
    'Adversarial machine learning',
    'Adversarial example',
    'Prompt injection',
    'Jailbreak (AI)',
    'Data poisoning',
    'Backdoor attack',
    'Membership inference attack',
    'Model inversion attack',
    'Model extraction attack',
    'Privacy in artificial intelligence',
    'Differential privacy',
    'Differentially private stochastic gradient descent',
    'Mechanistic interpretability',
    'Explainability',
    'Feature visualization',
    'Saliency map',
    'Integrated gradients',
    'Sparse autoencoder',
    'Superposition (neural networks)',
    'Induction head',
    'Probing classifier',
    'Representation engineering',
    'Algorithmic bias',
    'Fairness (machine learning)',
    'Sycophancy (artificial intelligence)',
    'Model collapse',
    'Shortcut learning',
    'Double descent',
    'Grokking (machine learning)',
    'Lottery ticket hypothesis',
    'Neural tangent kernel',
    # Multimodal transformers and additional neural foundations
    'Multimodal large language model',
    'Vision-language model',
    'Visual question answering',
    'Image captioning',
    'Contrastive Language-Image Pre-training',
    'BLIP (model)',
    'BLIP-2',
    'LLaVA',
    'Flamingo (language model)',
    'SigLIP',
    'ImageBind',
    'PaliGemma',
    'Diffusion transformer',
    'Masked autoencoder',
    'Data2vec',
    'Wav2vec',
    'HuBERT (model)',
    'SpeechT5',
    'AudioLM',
    'MusicLM',
    'MusicGen',
    'EnCodec',
    'Neural codec language model',
    'Connectionist temporal classification',
    'Cross-modal retrieval',
    'Multimodal fusion',
    'Joint embedding',
    'Self-distillation',
    'Siamese neural network',
    'Triplet loss',
    'Contrastive loss',
    'InfoNCE',
    'Noise-contrastive estimation',
    'Negative sampling',
    'SimCLR',
    'MoCo (machine learning)',
    'BYOL (machine learning)',
    'DINO (vision transformer)',
    'Hopfield network',
    'Boltzmann machine',
    'Restricted Boltzmann machine',
    'Energy-based model',
    'Echo state network',
    'Reservoir computing',
    'Liquid state machine',
    'Spiking neural network',
    'Radial basis function network',
    'Self-organizing map',
    'Neural ordinary differential equation',
    'Normalizing flow',
    'Invertible neural network',
    'Variational inference',
    'Reparameterization trick',
    'Evidence lower bound',
    'Mixture density network',
    'Graph attention network',
    'Message passing neural network',
    'Geometric deep learning',
    'Equivariant neural network',
]

# Preserve the existing seeds and add each new title only once.
WIKI_SEEDS = list(dict.fromkeys(WIKI_SEEDS + EXTRA_WIKI_TOPICS))

BACK_SECTIONS = {
    "see also", "references", "notes", "notes and references",
    "citations", "bibliography", "further reading", "external links",
    "sources", "footnotes",
}


class WikipediaClient:
    def __init__(self, delay=1.0, user_agent=None):
        self.delay = max(float(delay), 0.0)
        self.last_request = 0.0
        self.session = requests.Session()
        self.session.headers["User-Agent"] = user_agent or (
            "CPTWikipediaCollector/1.0 (https://huggingface.co/vinmlops)"
        )
        retry = Retry(
            total=3, backoff_factor=1,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["GET"], respect_retry_after_header=True,
        )
        self.session.mount("https://", HTTPAdapter(max_retries=retry))

    def query(self, **params):
        wait = self.delay - (time.monotonic() - self.last_request)
        if wait > 0:
            time.sleep(wait)
        try:
            response = self.session.get(
                API_URL,
                params={"format": "json", "formatversion": 2, **params},
                timeout=(10, 60),
            )
            response.raise_for_status()
            data = response.json()
            if "error" in data:
                raise ValueError(f"Wikipedia API error: {data['error']}")
            return data
        finally:
            self.last_request = time.monotonic()

    def page_info(self, title):
        data = self.query(
            action="query", titles=title, redirects=1,
            prop="info|pageprops|revisions", inprop="url", rvprop="ids",
        )
        pages = data.get("query", {}).get("pages", [])
        for page in pages:
            if not page.get("missing") and not page.get("invalid") and page.get("ns") == 0:
                return page
        return None

    def resolve(self, topic):
        # Exact titles/redirects take priority over potentially unrelated hits.
        page = self.page_info(topic)
        method = "title"
        if page is None:
            data = self.query(
                action="query", list="search", srsearch=topic,
                srnamespace=0, srlimit=1, srprop="",
            )
            hits = data.get("query", {}).get("search", [])
            if not hits:
                raise ValueError("no matching article found")
            page = self.page_info(hits[0]["title"])
            method = "search"
        if page is None:
            raise ValueError("search result is not an available article")
        if "disambiguation" in page.get("pageprops", {}):
            raise ValueError(
                f"{page['title']!r} is ambiguous; supply a more specific article title"
            )
        return page, method

    def article_html(self, revision_id):
        data = self.query(action="parse", oldid=revision_id, prop="text")
        return data["parse"]["text"]

    def close(self):
        self.session.close()


def extract_main_text(html):
    """Keep article prose, headings, lists, code and tables; remove page clutter.

    Math is retained as TeX when the HTML exposes it. Plain-text tables lose
    visual layout; this is text extraction, not a perfect article reproduction.
    """
    soup = BeautifulSoup(html, "html.parser")
    root = soup.select_one(".mw-parser-output") or soup
    for node in root.select(
        "script, style, noscript, .mw-editsection, .reference, .references, "
        ".reflist, .navbox, .vertical-navbox, .sidebar, .infobox, .hatnote, "
        ".ambox, .metadata, .toc, #toc, .catlinks, .sistersitebox, "
        ".noprint, .thumb, figure"
    ):
        node.decompose()

    for node in root.select(".mwe-math-element"):
        annotation = node.find("annotation", attrs={"encoding": "application/x-tex"})
        image = node.find("img", alt=True)
        formula = annotation.get_text() if annotation else (
            image.get("alt", "") if image else node.get_text(" ", strip=True)
        )
        node.replace_with(f" ${formula}$ " if formula else " ")
    for node in root.find_all("br"):
        node.replace_with("\n")

    blocks = []
    skip_level = None
    containers = {"ul", "ol", "dl", "table", "pre", "blockquote"}
    for node in root.find_all(["h2", "h3", "h4", "h5", "h6", "p", *sorted(containers)]):
        if any(parent.name in containers for parent in node.parents):
            continue
        if node.name.startswith("h"):
            level = int(node.name[1])
            title = node.get_text(" ", strip=True)
            if skip_level is not None and level <= skip_level:
                skip_level = None
            if skip_level is None and title.casefold().strip(" :") in BACK_SECTIONS:
                skip_level = level
            if skip_level is None and title:
                blocks.append(title)
            continue
        if skip_level is not None:
            continue
        if node.name == "pre":
            text = node.get_text().strip("\n")
        elif node.name == "table":
            text = "\n".join(
                " | ".join(cell.get_text(" ", strip=True) for cell in row.find_all(["th", "td"], recursive=False))
                for row in node.find_all("tr")
            )
        elif node.name in {"ul", "ol", "dl"}:
            # Use line boundaries without repeating nested list contents.
            text = node.get_text("\n", strip=True)
        else:
            text = re.sub(r"\s+", " ", node.get_text(" ", strip=True)).strip()
        if text.strip():
            blocks.append(text)
    return "\n\n".join(blocks).strip()


def collect_wikipedia(cfg, topics=None):
    settings = cfg["data"]
    topics = topics if topics is not None else settings.get("wiki_topics", WIKI_SEEDS)
    if not isinstance(topics, list) or not topics or any(
        not isinstance(topic, str) or not topic.strip() for topic in topics
    ):
        raise ValueError("topics must be a nonempty list of nonempty strings")
    topics = list(dict.fromkeys(topic.strip() for topic in topics))
    cap = int(settings.get("wiki_max_pages", len(topics)))
    min_chars = int(settings.get("wiki_min_chars", 800))
    if cap < 1 or min_chars < 1:
        raise ValueError("wiki_max_pages and wiki_min_chars must be positive")
    client = WikipediaClient(
        delay=settings.get("wiki_request_delay_sec", 1.0),
        user_agent=settings.get("wiki_user_agent"),
    )
    rows, seen = [], {}
    failed = duplicates = processed = 0
    try:
        for topic in topics:
            if len(rows) >= cap:
                break
            processed += 1
            try:
                page, method = client.resolve(topic)
                page_id = page["pageid"]
                print(f"[wikipedia] {topic!r} -> {page['title']!r} ({method})")
                if page_id in seen:
                    seen[page_id]["requested_topics"].append(topic)
                    duplicates += 1
                    continue
                revision_id = page["revisions"][0]["revid"]
                text = extract_main_text(client.article_html(revision_id))
                if len(text) < min_chars:
                    raise ValueError(f"only {len(text)} extracted characters; minimum is {min_chars}")
                row = {
                    "source": "wikipedia", "id": f"wiki:{page_id}",
                    "title": page["title"], "url": page["fullurl"],
                    "license": "CC-BY-SA-4.0",
                    "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
                    "revision_id": revision_id,
                    "revision_url": f"https://en.wikipedia.org/w/index.php?oldid={revision_id}",
                    "history_url": f"https://en.wikipedia.org/w/index.php?curid={page_id}&action=history",
                    "requested_topics": [topic], "selection_method": method,
                    "fetched_at": datetime.now(timezone.utc).isoformat(),
                    "text": text,
                }
                rows.append(row)
                seen[page_id] = row
            except (requests.RequestException, ValueError, KeyError, IndexError) as exc:
                failed += 1
                print(f"[wikipedia] SKIPPED {topic!r}: {exc}")
    finally:
        client.close()
    print(
        f"[wikipedia] collected={len(rows)}, skipped={failed}, "
        f"duplicate_pages={duplicates}, unprocessed={len(topics) - processed}"
    )
    if failed:
        print("[wikipedia] PARTIAL collection: review skipped topics above.")
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="day2.yaml")
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument("--topic", action="append", help="specific topic or article title; repeat as needed")
    selection.add_argument(
        "--all-topics", action="store_true",
        help="merge the expanded built-in list with YAML wiki_topics",
    )
    parser.add_argument(
        "--max-pages", type=int, default=None,
        help="override YAML wiki_max_pages; 0 attempts every selected topic",
    )
    args = parser.parse_args()

    # Use your existing helpers; do not create a replacement dataio.py.
    from dataio import ensure_dir, load_config, write_jsonl

    cfg = load_config(args.config)
    if args.max_pages is not None and args.max_pages < 0:
        parser.error("--max-pages must be zero or a positive integer")
    selected_topics = args.topic
    if args.all_topics:
        configured_topics = cfg["data"].get("wiki_topics", [])
        if not isinstance(configured_topics, list) or any(
            not isinstance(topic, str) or not topic.strip() for topic in configured_topics
        ):
            parser.error("data.wiki_topics must be a list of nonempty strings")
        selected_topics = list(dict.fromkeys(
            WIKI_SEEDS + [topic.strip() for topic in configured_topics]
        ))
    if args.max_pages is not None:
        effective_topics = (
            selected_topics if selected_topics is not None
            else cfg["data"].get("wiki_topics", WIKI_SEEDS)
        )
        if not isinstance(effective_topics, list) or not effective_topics:
            parser.error("select at least one topic")
        cfg["data"]["wiki_max_pages"] = args.max_pages or len(effective_topics)
    rows = collect_wikipedia(cfg, topics=selected_topics)
    if not rows:
        raise SystemExit("No articles collected. Existing output was not replaced.")
    raw_dir = Path(cfg["paths"]["raw_dir"])
    ensure_dir(str(raw_dir))
    target = raw_dir / "domain_wikipedia.jsonl"
    temporary = target.with_suffix(".jsonl.part")
    try:
        write_jsonl(str(temporary), rows)
        temporary.replace(target)
    finally:
        temporary.unlink(missing_ok=True)
    print(f"Saved {len(rows)} Wikipedia articles to {target}")
    print("Review topic-to-title matches above before cleaning and training.")
    print("Next: python collect.py --config day2.yaml --skip-wiki")


if __name__ == "__main__":
    main()
